-- 1. Hapus tabel lama jika sudah ada (mencegah error relation already exists)
DROP TABLE IF EXISTS transaksi_medis CASCADE;
DROP TABLE IF EXISTS persediaan CASCADE;
DROP TABLE IF EXISTS pasien CASCADE;

-- 2. Buat Tabel Pasien
CREATE TABLE pasien (
    id_pasien BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_pasien VARCHAR(100) NOT NULL,
    penjamin VARCHAR(50) DEFAULT 'Umum/Tunai',
    no_polis VARCHAR(50) DEFAULT '-',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Buat Tabel Persediaan
CREATE TABLE persediaan (
    id_item BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_item VARCHAR(100) NOT NULL,
    kategori VARCHAR(30) CHECK (kategori IN ('Obat', 'Alkes', 'Jasa Medis')),
    stok INT DEFAULT 0,
    harga_pokok NUMERIC(12, 2) DEFAULT 0,
    harga_jual NUMERIC(12, 2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Buat Tabel Transaksi Medis
CREATE TABLE transaksi_medis (
    id_transaksi BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pasien BIGINT REFERENCES pasien(id_pasien) ON DELETE CASCADE,
    id_item BIGINT REFERENCES persediaan(id_item) ON DELETE SET NULL,
    tanggal DATE DEFAULT CURRENT_DATE,
    jumlah INT DEFAULT 1,
    biaya_jasa NUMERIC(12, 2) DEFAULT 0,
    total_biaya NUMERIC(12, 2) NOT NULL,
    status_pembayaran VARCHAR(30) CHECK (status_pembayaran IN ('Lunas', 'Piutang Asuransi')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Insert Data Dummy Persediaan
INSERT INTO persediaan (nama_item, kategori, stok, harga_pokok, harga_jual) VALUES
('Paracetamol 500mg', 'Obat', 100, 2000, 5000),
('Amoxicillin 500mg', 'Obat', 50, 5000, 10000),
('Vitamin C 500mg', 'Obat', 80, 1500, 4000),
('Ibuprofen 400mg', 'Obat', 60, 3000, 7000),
('Spuit 3cc / Jarum', 'Alkes', 200, 1000, 3000),
('Kasa Steril Box', 'Alkes', 40, 8000, 15000);

-- 6. Insert Data Pasien Lengkap (Berbagai Penjamin)
INSERT INTO pasien (nama_pasien, penjamin, no_polis) VALUES
('Budi Santoso', 'Umum/Tunai', '-'),
('Siti Rahma', 'BPJS Kesehatan', '00012345678'),
('Ahmad Fauzi', 'Asuransi Prudential', 'PRU-992182'),
('Dewi Lestari', 'Mandiri Inhealth', 'MI-881203'),
('Rian Hidayat', 'Asuransi Manulife', 'MNL-441290'),
('Eka Putri', 'Umum/Tunai', '-'),
('Hendra Wijaya', 'BPJS Kesehatan', '00098765432');